
module Main where

import Test.Hspec

import qualified HigherKind as HigherKind
import qualified ObjectWithSingleFieldNoTagSingleConstructors as ObjectWithSingleFieldNoTagSingleConstructors
import qualified ObjectWithSingleFieldTagSingleConstructors as ObjectWithSingleFieldTagSingleConstructors
import qualified TaggedObjectNoTagSingleConstructors as TaggedObjectNoTagSingleConstructors
import qualified TaggedObjectTagSingleConstructors as TaggedObjectTagSingleConstructors
import qualified TwoElemArrayNoTagSingleConstructors as TwoElemArrayNoTagSingleConstructors
import qualified TwoElemArrayTagSingleConstructors as TwoElemArrayTagSingleConstructors
import qualified Untagged as Untagged

main = hspec $ do
  ObjectWithSingleFieldTagSingleConstructors.tests
  ObjectWithSingleFieldNoTagSingleConstructors.tests
  TaggedObjectTagSingleConstructors.tests
  TaggedObjectNoTagSingleConstructors.tests
  TwoElemArrayTagSingleConstructors.tests
  TwoElemArrayNoTagSingleConstructors.tests
  Untagged.tests
  HigherKind.tests
