name:                aeson-typescript
version:             0.6.4.0
github:              "codedownio/aeson-typescript"
license:             BSD3
category:            Text, Web, JSON
author:              "Tom McLaughlin"
maintainer:          "tom@codedown.io"
copyright:           "2022 CodeDown"

extra-source-files:
- README.md
- CHANGELOG.md
- test/assets/package.json
- test/assets/npm_install.sh
- test/assets/yarn_install.sh
- test/assets/yarn.lock

# Metadata used when publishing your package
synopsis:            Generate TypeScript definition files from your ADTs

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/codedownio/aeson-typescript#readme>

tested-with:
- GHC == 9.6.1
- GHC == 9.4.4
- GHC == 9.2.7
- GHC == 9.0.2
- GHC == 8.10.7
- GHC == 8.8.4
- GHC == 8.6.5

dependencies:
- aeson
- base >= 4.7 && < 5
- bytestring
- containers
- mtl
- string-interpolate
- template-haskell
- text
- th-abstraction
- transformers
- unordered-containers

default-extensions:
- LambdaCase
- MultiWayIf
- NamedFieldPuns
- OverloadedStrings
- QuasiQuotes
- RecordWildCards
- ScopedTypeVariables
- TupleSections
- ViewPatterns

library:
  source-dirs: src
  exposed-modules:
  - Data.Aeson.TypeScript.TH
  - Data.Aeson.TypeScript.Internal
  - Data.Aeson.TypeScript.Recursive
  - Data.Aeson.TypeScript.LegalName

tests:
  aeson-typescript-tests:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -haddock
    - -fno-warn-unused-top-binds
    - -fno-warn-orphans
    default-extensions:
    - FlexibleContexts
    - KindSignatures
    - TemplateHaskell
    - TypeFamilies
    dependencies:
    - aeson-typescript
    - bytestring
    - directory
    - filepath
    - hspec
    - process
    - temporary
